# Generated by Django 3.1.2 on 2020-10-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_tracker', '0006_auto_20201024_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='e_tracker.profile'),
        ),
    ]
